### ISSUE TITLE
Add `tensorflow` gitmodule

### ISSUE THREAD

**Issue by awatson1978** [clinical-meteor/software-development-kit#124]
https://github.com/tensorflow/tensorflow

**Comment by kaiyes** [comment]
here comes data science !

**Comment by awatson1978** [comment]
Yup!  :)

Good to hear from you!  Have you seen the new roadmap?  It's like a Trello board, but it integrates with GitHub.  Still need to adjust the columns a bit, but trying to give some visibility on what the roadmap looks like...
https://waffle.io/clinical-meteor/software-development-kit

Looking forward to getting Tensorflow into the framework....

**Comment by kaiyes** [comment]
Wafle.io looks awesome.

**Comment by awatson1978** [comment]
Completed
