### ISSUE TITLE
Clinical Meteor for CDISC Standards

### ISSUE THREAD

**Issue by nicholsn** [clinical-meteor/software-development-kit#135]
Hi, this is a very exciting effort - thank you for working on it! 

Has anyone looked at creating a clinical-meteor subproject for the CDISC standards (e.g., SDTM and ADaM) for modeling data from clinical trials and studies? 

I ask because I am interested in building up a repository of clinical trial data modeled using these standards. Do you think there are  components of the clinical-meteor sdk that would help with this effort? If so, what should I be looking at?

Thanks!

**Comment by awatson1978** [comment]
@mcrayne is the person to answer this question.  

We have the following two projects, which have some tentative work in this area:  
https://github.com/clinical-meteor/clinical-trials  
https://github.com/clinical-meteor/ckcc  

I'm also working on making sure we support the FHIR ResearchSubject and ResearchStudy resources; which will provide interoperability with ClinicalTrials.gov.  

https://www.hl7.org/fhir/researchsubject.html  
https://www.hl7.org/fhir/researchstudy.html  

Lastly, we had the folks from MolecularMatch reach out; and have some very preliminary ideas on how to include supplement apps with some peer-reviewed evidence based medicine.  
https://api.molecularmatch.com

But as for CDISC standards; I'm not an expert in that area.  I'm happy to accept pull requests with data formatted according to SDTM, ADaM, etc.   Or parsers that can scan such data.  Etc.

**Comment by nicholsn** [comment]
great, thanks for the resources. The two projects look like a good starting place for how to build what I have in mind for cdisc, actually the way you have each of the hl7 resources organized as modules could be a nice way to model the observation domains in SDTM.

Does clinical-meteor have a set of best practices documented somewhere? Or is there a notion of being a 'clinical-meteor' compliant app?

**Comment by awatson1978** [comment]
Well, there's the project homepage (which needs a redesign) which describes general architecture.
http://clinical.meteorapp.com/ 

Best practices are basically what's documented in the Meteor docs; with the exception that we use Nightwatch/Gagarin for our QA infrastructure.  
http://docs.meteor.com/  

If you're using our base packages or using the `--release clinical:METEOR@1.4.2-rc17` flag when launching your Meteor app, then you're definitely running a Clinical Meteor app.

For compliance, I think we're heading towards measuring that in terms of FHIR compliance, and using the [CapabilityStatement](https://www.hl7.org/fhir/capabilitystatement.html) resource, and testing utilities like Touchstone and Crucible.

**Comment by nicholsn** [comment]
Cool, thanks again - very helpful to have a best practices to follow out of the gate!
