### ISSUE TITLE
Gitbook?

### ISSUE THREAD

**Issue by PEM--** [clinical-meteor/software-development-kit#24]
Hi,

Thx for the nice write up. It has teach me a couple of nice features and tricks.

I was wondering wether it would be possible that you add [Gitbook](http://www.gitbook.io/)?

PEM

**Comment by awatson1978** [comment]
The Meteor Cookbook is now available on [StackOverflow Documentation](http://stackoverflow.com/documentation/meteor/topics)!  

Unfortunately, GitBook never quite worked out.  However, StackOverflow Documentation represents many of the same ideas that GitBook offered, such as collaborative editing and community maintenance; but with a far better development team, community reach, editing tools, documentation formatting, etc.
