### ISSUE TITLE
First Production Deployment

### ISSUE THREAD

**Issue by ccorcos** [clinical-meteor/software-development-kit#34]
I've used  `mup` before to deploy to digital ocean but nothing special. I pretty much always just use `meteor deploy` because its so easy! 

But now I'm looking to deploy a real production server that needs to handle some scale and I have no idea how to do this. Ive read a bunch of stuff in a bunch of different places but I haven't found a simple opinionated post giving an example.

I've read about oplog support so you can have multiple mongo servers. I've heard you can get mongohq to host your mongo server and they'll do this for you and create backups for you.

I've read about using AWS with collectionFS to host uploaded images, etc.

And I read through the very brief article on here about deploying the front end only to modulus. 

To be honest, I just don't know how this all fits together. I would really appreciate it if you could write a bit more on this topic giving an example of a specific way of deploying a production server that is going to scale and how to tie everything together.

Thanks

**Comment by awatson1978** [comment]
Hi!  Meteor Cookbook has been migrated to [StackOverflow Documentation](http://stackoverflow.com/documentation/meteor/3377/deployment-with-upstart#t=201607270127127399651).  We have at least one article on production deployment, with more examples to come.
