### ISSUE TITLE
Tabbed Workflow - Idea

### ISSUE THREAD

**Issue by benjamin79** [clinical-meteor/software-development-kit#51]
With multiple-tabs it can get slow cause all templates get created immediately . What about the following?

html:
```
{{> DynamicTemplate template=getTemplate}}
```

js:
```
Template.Something.helpers({

  getTemplate: function () {

    if(Session.get('selectedPanel') === 1){
      return "firstPanel";
    };

    if(Session.get('selectedPanel') === 2){
      return "secondPanel";
    };
...
```

**Comment by awatson1978** [comment]
This MeteorCookbook article has has been migrated over to [StackOverflow Documentation](http://stackoverflow.com/documentation/meteor/4202/blaze-user-interface-recipes-bootstrap-no-jquery#t=201607271445003630413)!  Public comments and edits are encouraged!  :)

ps.  Apologies for never acting on this.  I tend not to use DynamicTemplate, and have been unsure how to evaluate this particular suggestion for well over a year now.  Feel free to copy/paste it to StackOverflow as an edit, and maybe we can get some more people to comment and improve it!
