### ISSUE TITLE
settings.json

### ISSUE THREAD

**Issue by javaknight** [clinical-meteor/software-development-kit#59]
How can you make a settings.json "setup" that uses values declared elsewhere? eg, consider the following.. in C, a sample.h file (psuedo-c)

#define TITLE = "great success"
#define MEDIA = "book"

#define DOGS TITLE+" "+MEDIA+" "+" for dogs"
#define CATS TITLE+" "+MEDIA+" "+" for cats"
#define ELEPHANTS TITLE+" "+MEDIA+" "+" for elephants"
.. insert 1000 more animals here ...

The point is, I don't want to manage the same string in a JSON definition multiple times (in this case, TITLE and MEDIA) - I want to reuse it as a constant definition. But JSON is defined all at once, which (as far as I can tell?) makes this impossible in settings.json for Meteor. 

So the following JSON is invalid, even though it represents the idea of what I want:
{
  "TITLE" : "great success",
  "MEDIA" : "book",
  "animals" : 
  {
     "DOGS" : TITLE+" "+MEDIA+" "+for dogs",
     "CATS" : TITLE+" "+MEDIA+" "+for cats",
     "ELEPHANTS" : TITLE+" "+MEDIA+" "+for elephants",
     ... 1000 more json definitions here ...
  }
}

**Comment by awatson1978** [comment]
The MeteorCookbook is being migrated over to [StackOverflow Documentation](http://stackoverflow.com/documentation/meteor/4198/environment-detection/14699/advanced-environment-configurations#t=201607271654085379941)!  Please see the **Advanced Environment Configurations** section in ``Environment Detection`` for more information on this; and please feel free to submit comments and code examples to our new collaborative documentation system!
