### ISSUE TITLE
the code in writing.unit.tests.with.jasmine.md doesn't exist in the example repo

### ISSUE THREAD

**Issue by Maxhodges** [clinical-meteor/software-development-kit#71]
```
describe("Template.leaderboard.players", function () {
 it("asks for the players to be primarily in descending score order, then in alphabetical order and returns as is", function () {
        var someLocalCollectionCursor = {};
```

https://github.com/awatson1978/meteor-cookbook/blob/master/cookbook/writing.unit.tests.with.jasmine.md#write-your-unit-tests

**Comment by awatson1978** [comment]
The MeteorCookbook is being migrated over to [StackOverflow Documentation](http://stackoverflow.com/documentation/meteor).  As I've never been a big user of Jasmine, this topic is probably getting deprecated and removed from the Clinical Meteor SDK; and we're going to let the community develop better documentation using the new StackOverflow collaborative documentation editing tools.
