### ISSUE TITLE
File structure: Is server/collections.initialize.js/  or server/collections.initialize.js

### ISSUE THREAD

**Issue by yoonghm** [clinical-meteor/software-development-kit#83]
Under the recommended file structure, should ```server/collections.initialize.js/ ``` be ```server/collections.initialize.js``` instead?

**Comment by awatson1978** [comment]
Probably.  However, we're doing a lot of editing as the MeteorCookbook is being migrated to [StackOverflow Documentation](http://stackoverflow.com/documentation/meteor/3072/directory-structure#t=201607270057106544704).  Check there for the latest.
